version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: rynok-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rynok
      POSTGRES_PASSWORD: rynok
      POSTGRES_DB: rynok
    ports:
      - "5432:5432"
    volumes:
      - rynok_pgdata:/var/lib/postgresql/data

volumes:
  rynok_pgdata: